import { ArtistsStoreProvider } from "@/app/(artists)/providers/artists-store";
import Navbar from "@/app/components/navbar";
import "@/app/globals.css";
import { GameStoreProvider } from "@/app/providers/game-store";
import type { Metadata } from "next";
import { Gabarito, Outfit } from "next/font/google";

const gabarito = Gabarito({
  subsets: ["latin"],
  fallback: ["sans-serif"],
  variable: "--font-gabarito",
});

const outfit = Outfit({
  weight: "800",
  subsets: ["latin"],
  fallback: ["sans-serif"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Track Battle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${gabarito.variable} ${outfit.variable} relative antialiased`}
      >
        <Navbar />
        <div className="m-auto h-[calc(100dvh-56px)] min-h-[650px] max-w-[1920px]">
          <GameStoreProvider>
            <ArtistsStoreProvider>{children}</ArtistsStoreProvider>
          </GameStoreProvider>
        </div>
      </body>
    </html>
  );
}
